# Generated by Django 3.2.8 on 2021-11-08 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_genre_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cinema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cinema'),
        ),
    ]
